#!/bin/bash -xe

exec 2>&1

export JAVA_HOME=$(hab pkg path core/jre8)
export JENKINS_CONFIG={{pkg.svc_config_path}}
export JENKINS_HOME={{pkg.svc_data_path}}/jenkins


LD_LIBRARY_PATH="$(hab pkg path core/gcc-libs)/lib"
export LD_LIBRARY_PATH
echo "LD_LIBRARY_PATH=${LD_LIBRARY_PATH}"

exec $(hab pkg path core/openssh)/sbin/sshd -D -f {{pkg.svc_config_path}}/sshd_config
